version: "3.8"

services:
  react-app:
    build:
      context: ./recursos-humanos
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - spring-api

  spring-api:
    build:
      context: ./rh
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/recursos-humanos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recursos-humanos
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: